theme = "tokyonight_storm"

[editor]
mouse = true
cursorline = true
true-color = true
color-modes = true
completion-replace = true
insert-final-newline = true
trim-trailing-whitespace = true
bufferline = "multiple"
line-number = "relative"
end-of-line-diagnostics = "hint"

clipboard-provider = "termux"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "â•Ž"
skip-levels = 0

[editor.gutters.line-numbers]
min-width = 1

[editor.auto-save]
after-delay.enable = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[keys.normal.space]
e = { w = ":write", c = ":bc", x = ":bco", l = ":toggle lsp.display-inlay-hints" }
q = ":quit"

[keys.normal."+"]
f = ":format"
w = ":toggle whitespace.render all"
W = ":set whitespace.render none"
s = ":toggle soft-wrap.enable"

[keys.normal.space.f]
f = "file_picker_in_current_directory"
F = "file_picker"
b = "file_picker_in_current_buffer_directory"
"." = ":toggle-option file-picker.git-ignore"
g = "global_search"
e = "file_explorer"
r = ":reload-all"
